name: layout
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1
  geolocator: ^13.0.2
  # Mapas (OpenStreetMap) — funciona no Flutter Web sem API key
  flutter_map: ^8.0.0
  latlong2: ^0.9.0
  # Chamada à API OSRM para obter geometria da rota entre dois pontos

  http: ^1.6.0

   # Sensores de hardware (acelerômetro e giroscópio)
  sensors_plus: ^6.1.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo_e-festa.png
